services:
  db:
    image: mysql:8.4.5
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graphql_db

volumes:
  mysql_data:
    driver: local
