apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ${API_IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "500Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
